linters:
- import:
    packages: ['iodata']
- namespace:
    filefilter: ['- */__init__.py', '- */test_*.py', '- *setup.py', '- tools/*',
                 '+ *.py', '+ *.pyx']
- pylint:
    config: .pylintrc
- pycodestyle:
    config: .pycodestylerc
- pydocstyle:
- whitespace:
