package:
  version:  "{{ PROJECT_VERSION }}" 
  name: 'flik'

source:
  path: ../../

build:
  number: 0
  script: python setup.py install

requirements:
  run:
    - python
    - numpy
    - nose
  build:
    - python
    - numpy
    - nose
    - setuptools

about:
  dev_url: https://github.com/QuantumElephant/Flik
  description: An experimental local optimization package 
  license: GNU General Public License v3 or later (GPLv3+)
  license_family: GPL3
  home: https://github.com/QuantumElephant/Flik
  license_file: LICENSE.txt
  doc_url: https://github.com/QuantumElephant/Flik

extra:
  recipe-maintainers: Ayers Lab <ayers@mcmaster.ca>
